### ISSUE TITLE
todo time_picker_issue

### ISSUE THREAD

**Issue by luigimanco** [alexmanni/LAB1mad#8]
in https://github.com/alexmanni/LAB1mad/commit/fc3af65f5f8d5ecdb0dd77184e0ceb69c0150f00 :
- [ ] time interval isn't correctly set as button text (e.g. 8:00 - 21:00 to monday_time) 
- [x] https://github.com/alexmanni/LAB1mad/commit/88594fd6ecdd841bbb728bdb22748b8c29433246 should discriminate between monday-sunday _time  and also morning and evening times
- [ ]  title of timePicker not shown 
- [ ] opening hours should also be saved in SharedPreferences (use helper class)
